"""Generate ``llms.txt`` — a machine-readable index of the course for AI assistants.

Scans ``notebooks/``, extracts each notebook's title and one-line purpose, groups them by
module folder, and writes ``llms.txt`` at the repo root. Re-run whenever notebooks change
(or wire into CI / a pre-commit hook) so the index never goes stale:

    uv run python scripts/gen_llms_txt.py
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NB_DIR = ROOT / "notebooks"
OUT = ROOT / "llms.txt"


def _first_markdown_lines(nb: dict) -> list[str]:
    """Return the source lines of a notebook's first markdown cell."""
    for cell in nb.get("cells", []):
        if cell.get("cell_type") == "markdown":
            src = cell.get("source", [])
            return [ln.rstrip("\n") for ln in (src if isinstance(src, list) else [src])]
    return []


def title_and_purpose(nb_path: Path) -> tuple[str, str]:
    """Extract (title, purpose) from a notebook's header markdown cell.

    Title = the first ``# `` heading (falls back to the file stem). Purpose = the first prose
    line after a ``## Purpose`` heading, else the first non-heading prose line.
    """
    lines = _first_markdown_lines(json.loads(nb_path.read_text()))
    title = nb_path.stem
    for ln in lines:
        if ln.startswith("# "):
            title = ln[2:].strip()
            break
    purpose, after_purpose = "", False
    for ln in lines:
        s = ln.strip()
        if s.lower().startswith("## purpose"):
            after_purpose = True
            continue
        if after_purpose and s:
            purpose = s
            break
    if not purpose:
        for ln in lines:
            s = ln.strip()
            if s and not s.startswith("#") and not s.startswith("**"):
                purpose = s
                break
    return title, purpose


def build_llms_txt() -> str:
    """Build the full llms.txt content from the notebooks on disk."""
    nbs = sorted(
        p for p in NB_DIR.rglob("*.ipynb") if ".ipynb_checkpoints" not in p.parts
    )
    out = [
        "# Quantum Optimal Transport — Hands-On Course",
        "",
        "> Machine index for AI assistants. Each entry: notebook path — title — purpose.",
        "> Generated by scripts/gen_llms_txt.py (do not hand-edit). See AGENTS.md for how to tutor.",
        "",
    ]
    current_group = None
    for p in nbs:
        group = p.parent.relative_to(NB_DIR).as_posix()
        group = "(flat)" if group in (".", "") else group
        if group != current_group:
            out.append(f"## {group}")
            current_group = group
        title, purpose = title_and_purpose(p)
        rel = p.relative_to(ROOT).as_posix()
        line = f"- [{rel}]({rel}) — {title}"
        if purpose:
            line += f" — {purpose}"
        out.append(line)
    out.append("")
    return "\n".join(out)


if __name__ == "__main__":
    OUT.write_text(build_llms_txt())
    print(f"wrote {OUT.relative_to(ROOT)} ({len(OUT.read_text().splitlines())} lines)")
